export const models = [
  { value: '718', label: '718' },
  { value: '911', label: '911' },
  { value: '918', label: '918' },
  { value: 'taycan', label: 'Taycan' },
  { value: 'panamera', label: 'Panamera' },
  { value: 'macan', label: 'Macan' },
  { value: 'cayenne', label: 'Cayenne' },
]

export const trimsByModel = {
  718: [
    { value: 'cayman', label: 'Cayman' },
    { value: 'cayman_t', label: 'Cayman T' },
    { value: 'cayman_s', label: 'Cayman S' },
    { value: 'cayman_gts', label: 'Cayman GTS 4.0' },
    { value: 'cayman_gt4', label: 'Cayman GT4' },
    { value: 'cayman_gt4rs', label: 'Cayman GT4 RS' },
    { value: 'spyder', label: 'Spyder' },
    { value: 'boxster', label: 'Boxster' },
    { value: 'boxster_t', label: 'Boxster T' },
    { value: 'boxster_s', label: 'Boxster S' },
    { value: 'boxster_gts', label: 'Boxster GTS 4.0' },
  ],
  911: [
    { value: 'carrera', label: 'Carrera' },
    { value: 'carrera_4', label: 'Carrera 4' },
    { value: 'carrera_s', label: 'Carrera S' },
    { value: 'carrera_4s', label: 'Carrera 4S' },
    { value: 'carrera_gts', label: 'Carrera GTS' },
    { value: 'carrera_4_gts', label: 'Carrera 4 GTS' },
    { value: 'carrera_cab', label: 'Carrera Cabriolet' },
    { value: 'carrera_4_cab', label: 'Carrera 4 Cabriolet' },
    { value: 'carrera_cab_s', label: 'Carrera S Cabriolet' },
    { value: 'carrera_cab_4s', label: 'Carrera 4S Cabriolet' },
    { value: 'carrera_cab_gts', label: 'Carrera GTS Cabriolet' },
    { value: 'carrera_cab_4_gts', label: 'Carrera 4 GTS Cabriolet' },
    { value: 'targa_4', label: 'Targa 4' },
    { value: 'targa_4s', label: 'Targa 4S' },
    { value: 'targa_gts', label: 'Targa GTS' },
    { value: 'edition_50', label: 'Edition 50 Years' },
    { value: 'turbo', label: 'Turbo' },
    { value: 'turbo_s', label: 'Turbo S' },
    { value: 'turbo_cab', label: 'Turbo Cabriolet' },
    { value: 'turbo_s_cab', label: 'Turbo S Cabriolet' },
    { value: 'gt3', label: 'GT3' },
    { value: 'gt3_touring', label: 'GT3 Touring' },
    { value: 'gt3rs', label: 'GT3 RS' },
    { value: 'sport_classic', label: 'Sport Classic' },
  ],
  918: [{ value: 'none', label: 'none' }],
  taycan: [
    { value: 'none', label: 'none' },
    { value: '4s', label: '4s' },
    { value: 'gts', label: 'GTS' },
    { value: 'turbo', label: 'Turbo' },
    { value: 'turbo_s', label: 'Turbo S' },
    { value: '4_cross_turismo', label: '4 Cross Turismo' },
    { value: '4s_cross_turismo', label: '4S Cross Turismo' },
    { value: 'gts_cross_turismo', label: 'GTS Cross Turismo' },
    { value: 'turbo_cross_turismo', label: 'Turbo Cross Turismo' },
    { value: 'turbo_s_cross_turismo', label: 'Turbo S Cross Turismo' },
  ],
  panamera: [
    { value: 'none', label: 'none' },
    { value: '4s', label: '4s' },
    { value: 'platinum_edition', label: 'Platinum Edition' },
    { value: '4', label: '4' },
    { value: '4_platinum_edition', label: '4 Platinum Edition' },
    { value: '4_exec', label: '4 Executive' },
    { value: '4_st', label: '4 Sport Turismo' },
    { value: '4s_exec', label: '4S Executive' },
    { value: '4s_st', label: '4S Sport Turismo' },
    { value: '4_eh', label: '4 E-Hybrid' },
    { value: '4_eh_platinum_edition', label: '4 E-Hybrid Platinum Edition' },
    { value: '4_eh_exec', label: '4 E-Hybrid Executive' },
    { value: '4_eh_st', label: '4 E-Hybrid Sport Turismo' },
    { value: '4s_eh', label: '4S E-Hybrid' },
    { value: '4s_eh_exec', label: '4S E-Hybrid Executive' },
    { value: '4s_eh_st', label: '4S E-Hybrid Sport Turismo' },
    { value: 'gts', label: 'GTS' },
    { value: 'gts_st', label: 'GTS Sport Turismo' },
    { value: 'turbo_s', label: 'Turbo S' },
    { value: 'turbo_s_exec', label: 'Turbo S Executive' },
    { value: 'turbo_s_st', label: 'Turbo S Sport Turismo' },
    { value: 'turbo_s_eh', label: 'Turbo S E-Hybrid' },
    { value: 'turbo_s_eh_exec', label: 'Turbo S E-Hybrid Executive' },
    { value: 'turbo_s_eh_st', label: 'Turbo S E-Hybrid Sport Turismo' },
  ],
  macan: [
    { value: 'none', label: 'none' },
    { value: 's', label: 'S' },
    { value: 't', label: 'T' },
    { value: 'gts', label: 'GTS' },
  ],
  cayenne: [
    { value: 'none', label: 'none' },
    { value: 's', label: 'S' },
    { value: 't', label: 'T' },
    { value: 'gts', label: 'GTS' },
    { value: 'platinum_edition', label: 'Platinum Edition' },
    { value: 'coupe', label: 'Coupe' },
    { value: 'coupe_platinum_edition', label: 'Coupe Platinum Edition' },
    { value: 'eh', label: 'E-Hybrid' },
    { value: 'eh_platinum_edition', label: 'E-Hybrid Platinum Edition' },
    { value: 'eh_coupe', label: 'E-Hybrid Coupe' },
    {
      value: 'eh_coupe_platinum_edition',
      label: 'E-Hybrid Coupe Platinum Edition',
    },
    { value: 's_platinum_edition', label: 'S Platinum Edition' },
    { value: 's_coupe', label: 'S Coupe' },
    { value: 's_coupe_platinum_edition', label: 'S Coupe Platinum Edition' },
    { value: 'gts_coupe', label: 'GTS Coupe' },
    { value: 'turbo', label: 'Turbo' },
    { value: 'turbo_coupe', label: 'Turbo Coupe' },
    { value: 'turbo_s_eh', label: 'Turbo S E-Hybrid' },
    { value: 'turbo_s_eh_coupe', label: 'Turbo S E-Hybrid Coupe' },
    { value: 'turbo_gt', label: 'Turbo GT' },
  ],
}
